# Generated by Django 6.0.3 on 2026-04-04 17:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('document_proof', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('previous_report', models.FileField(blank=True, null=True, upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('existing_diseases', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('agreement', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
