# Generated by Django 6.0.3 on 2026-04-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='existing_diseases',
            field=models.CharField(blank=True, choices=[('Diabetes', 'Diabetes'), ('BP', 'Blood Pressure'), ('Heart', 'Heart Disease'), ('Asthma', 'Asthma')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
