# Generated by Django 6.0.3 on 2026-04-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0003_alter_patient_existing_diseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
