# Generated by Django 6.0.3 on 2026-04-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0004_remove_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='existing_diseases',
            field=models.CharField(blank=True, choices=[('Diabetes', 'Diabetes'), ('BP', 'Blood Pressure'), ('Heart', 'Heart Disease'), ('Asthma', 'Asthma')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
