# Generated by Django 6.0.3 on 2026-04-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0005_alter_patient_existing_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='existing_diseases',
            field=models.CharField(blank=True, choices=[('Diabetes', 'Diabetes'), ('BP', 'Blood Pressure'), ('Heart', 'Heart Disease'), ('Asthma', 'Asthma')], default='', max_length=100, null=True),
        ),
    ]
