# Generated by Django 6.0.3 on 2026-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0006_alter_patient_existing_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='existing_diseases',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
